image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - check
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache bash
  - docker info
  - npm install -g nx
  - npm install

check:
  stage: check
  script:
    - npx nx affected:apps --plain > affected_apps.txt
  artifacts:
    paths:
      - affected_apps.txt

build:
  stage: build
  script:
    - |
      if grep -q "app1" affected_apps.txt; then
        npx nx run app1:docker-build;
      fi
    - |
      if grep -q "app2" affected_apps.txt; then
        npx nx run app2:docker-build;
      fi

test:
  stage: test
  script:
    - |
      if grep -q "app1" affected_apps.txt; then
        docker-compose up -d app1;
        npx nx run app1:docker-test;
        npx nx run app1:docker-stop;
      fi
    - |
      if grep -q "app2" affected_apps.txt; then
        docker-compose up -d app2;
        npx nx run app2:docker-test;
        npx nx run app2:docker-stop;
      fi

#deploy:
#  stage: deploy
#  script:
#    - if grep -q "app2" affected_apps.txt; then docker-compose run app2 npm test; fi

#deploy:
#  stage: deploy
#  script:
#


#CI:
#  interruptible: true
#  only:
#    - main
#    - merge_requests
#  script:
    # This enables task distribution via Nx Cloud
    # Run this command as early as possible, before dependencies are installed
    # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
#    - npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

#    - npm ci --legacy-peer-deps
#    - NX_HEAD=$CI_COMMIT_SHA
#    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

    # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
    # - npx nx-cloud record -- echo Hello World
    # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
#    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint test build
#    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel 1 -t e2e-ci
